### ISSUE TITLE
Error:  'tuple' object has no attribute 'eval'

### ISSUE THREAD

**Issue by YoannT** [denmoroz/tensorflow-scrnn#1]
Hello, I don't know if anyone is going to read this, but there seems to be an error in the file ptb_word_lm.py.

Line 270:
state = m.initial_state.eval()

leads to:
AttributeError: 'tuple' object has no attribute 'eval'

I tried to convert m.initial_state to a tensor, and to use session.run instead of eval, but the next session.run int the 'for' loop then produces another error.

Would there be any way to fix this?

**Comment by denmoroz** [comment]
Seems like a trouble with LSTM cell, right?

Code is quite outdated and was used just for fast test of SCRNN cell. I'll fix it if someone is interested in it :)

**Comment by YoannT** [comment]
Thanks for your answer.

I would indeed be interested, as a project partner and I have to use this type of cell.

I'll keep you updated if we manage to make it work.

Have a good day.

**Comment by denmoroz** [comment]
Thanks!
I am mostly interested in porting this part of code as Keras (keras.io) layer. I use keras as main tool for my experiments because of its usability, nice API and possibility to run both on Theano and TensorFlow.

If it is not a secret, for what purpose you are interested in SCRNN? Why not standard LSTM / GRU?

**Comment by YoannT** [comment]
We have to study the effects of the variation of different parameters of this model of NN, as implemented in the Facebook paper.

We tried to use the original implementation in Torch but, probably due to modifications of the packages, we couldn't install the needed Lua libraries, that's why we tried with your Tensorflow version.

**Comment by YoannT** [comment]
Well we went the easy way by using previous versions of tensorflow and cuda and everything works well.

Sorry for not managing to make it work on the latest versions.

Issue closed, have a good day!
